### ISSUE TITLE
Custom tus upload metadata

### ISSUE THREAD

**Issue by goto-bus-stop** [transloadit/uppy-server#28]
Transloadit tus uploads need an `assembly_url` in the `Upload-Metadata` to tell the TL API which assembly an upload belongs to. At the moment uppy-server only passes the `filename` in the upload metadata (https://github.com/transloadit/uppy-server/blob/master/src/server/Uploader.js#L55)

It'd be really neat if we could specify custom tus metadata when POSTing to uppy-server, so we could add an assembly_url etc in here:
https://github.com/transloadit/uppy/blob/master/src/plugins/Tus10.js#L197

**Comment by goto-bus-stop** [comment]
For reference, this is the tus metadata that the uppy transloadit plugin would like to send along:

https://github.com/transloadit/uppy/blob/master/src/plugins/Transloadit/index.js#L89-L93

**Comment by Acconut** [comment]
> Transloadit tus uploads need an assembly_url in the Upload-Metadata to tell the TL API which assembly an upload belongs to. At the moment uppy-server only passes the filename in the upload metadata

You will also need a fieldname property, along side with assembly_url and filename.

**Comment by ifedapoolarewaju** [comment]
@goto-bus-stop @Acconut should [this](https://github.com/transloadit/uppy-server/commit/011dadbe476cd1a1d21fff5557cc2cf20c8d19dd) fix it?

**Comment by goto-bus-stop** [comment]
Yep, it should, thank you! 🎉

**Comment by ifedapoolarewaju** [comment]
fixed [here](https://github.com/transloadit/uppy-server/commit/011dadbe476cd1a1d21fff5557cc2cf20c8d19dd)
