### ISSUE TITLE
Can't have UPPY_ENDPOINTS on different protocol to UPPYSERVER_PROTOCOL

### ISSUE THREAD

**Issue by pauln** [transloadit/uppy-server#36]
As it currently stands, `uppy-server` is forcing the protocol specified by `UPPYSERVER_PROTOCOL` on all hosts listed in `UPPY_ENDPOINTS`.  This means that it is not possible to run `uppy-server` on HTTPS and connect an `uppy` running on HTTP (such as a development server running on `localhost`), as the `Access-Control-Allow-Origin` header won't be set as the HTTP origin won't be found in the whitelist.

In order to preserve backwards compatibility, perhaps the best way to handle this is to check for the presence of a protocol before prepending a protocol; that would allow existing configurations to continue to work unimpeded, but allow a protocol to be specified on any domain in the whitelist in order to specify one other than `UPPYSERVER_PROTOCOL`.

**Comment by ifedapoolarewaju** [comment]
@pauln thank you for reporting this. This was an intended behavior to enforce that the protocol set by uppy-server. But given the use case, I think it does make to allow the flexibility, since the whitelist is also provided on the server.

I am going to add a fix for this, thanks 🙂

**Comment by pauln** [comment]
This has been implemented in bdcce9e836de4cbb0ea47c59279ce100b1024130 - and seems to be working perfectly.  Thanks, @ifedapoolarewaju!
