### ISSUE TITLE
no cookie-parser dependency causes TypeError

### ISSUE THREAD

**Issue by kylerberry** [transloadit/uppy-server#39]
`TypeError: Cannot read property 'uppyAuthToken' of undefined
    at ...node_modules/uppy-server/lib/uppy.js:114:36`

https://github.com/transloadit/uppy-server/blob/master/src/uppy.js#L108 should have a fallback if cookies is `undefined` on the req object. And/or documentation should be made to make it clear

**Comment by ifedapoolarewaju** [comment]
@kylerberry Aye! I think it might be better to not even use cookies at all, and we can send this as part of the header or response. I'll work on this.

Thank you for reporting! 🙂

**Comment by ifedapoolarewaju** [comment]
I have made the use of `cookie-parser` internal to uppy, so any server using uppy-server doesn't have to require cookie-parser.

I am sticking with cookie-parser because it serves as an "out of the box" storage, and no additional implementation is required on the client to make it work.

**Comment by kylerberry** [comment]
@ifedapoolarewaju works for me. Thanks! 🌮

**Comment by ifedapoolarewaju** [comment]
closing this, as it has been fixed [here](https://github.com/transloadit/uppy-server/commit/b9f9396e9f212dde682ee2446bbc7db6dc46c596)
