### ISSUE TITLE
Google Drive provider not found in standalone mode

### ISSUE THREAD

**Issue by elluminatte** [transloadit/uppy-server#41]
Hi there

Looks like Google Drive integration doesnt work properly in standalone mode.

**Preconditions:**

1. uppy-server 0.9.0 running in docker container (standalone mode)
1. went to Google Drive tab, press Authenticate button
1. Google login form displayed - entered credentials and logged in

![1](https://user-images.githubusercontent.com/8599788/33514630-23e540c4-d768-11e7-8fca-a379e1fac488.png)

**Expected result:**

1. Returned to my site, Drive explorer is opened

**Actual result:**

1. Facing error

![2](https://user-images.githubusercontent.com/8599788/33514638-45759d24-d768-11e7-94ec-35ddd646f063.png)

2. Message from docker container

![3](https://user-images.githubusercontent.com/8599788/33514642-5097ed92-d768-11e7-83cc-53c054bdf07e.png)

```
(uppy_1  | uppy: Invalid provider options detected. Provider will not be loaded
uppy_1  |  Error: Not Found
uppy_1  |     at app.use (/app/src/standalone/index.js:110:15)
uppy_1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
uppy_1  |     at trim_prefix (/app/node_modules/express/lib/router/index.js:312:13)
uppy_1  |     at /app/node_modules/express/lib/router/index.js:280:7
uppy_1  |     at Function.process_params (/app/node_modules/express/lib/router/index.js:330:12)
uppy_1  |     at next (/app/node_modules/express/lib/router/index.js:271:10)
uppy_1  |     at /app/node_modules/express/lib/application.js:232:9
uppy_1  |     at /app/node_modules/express/lib/router/index.js:618:15
uppy_1  |     at next (/app/node_modules/express/lib/router/index.js:256:14)
uppy_1  |     at next (/app/node_modules/express/lib/router/route.js:121:14) 
uppy_1  | ::ffff:172.20.0.3 - - [02/Dec/2017:10:50:55 +0000] "GET /google/redirect?state)
```

3. Figured out that error happens in **lib/server/provider/index.js**:
 * **if (providers[providerName] ...)** - provider name is google (according action name is URL, see first attach)
 * there is no **providers['google']** element, but there is **providers['drive']**

So please fix this or tell me what am i doing wrong.

Regards, Nikolay

**Comment by ifedapoolarewaju** [comment]
oops this has been fixed, I forgot to release a patch for it! I’ll do so right away

Ifedapo Olarewaju  | Software Developer
Mobile: +2347083455063 | ifedapoolarewaju@gmail.com

**Comment by ifedapoolarewaju** [comment]
@elluminatte I have released a version 0.9.2 for this, please let me know if it works for you

**Comment by ifedapoolarewaju** [comment]
@elluminatte I misunderstood your comment earlier, and mistook your issue for something else.

The issue you are experiencing is most likely due to some inconsistent configuration. Do you mind sharing what your config is like? You can mask out important credentials :)

**Comment by elluminatte** [comment]
@ifedapoolarewaju of course, this is my config:

```
UPPYSERVER_SECRET=blabla
UPPYSERVER_DOMAIN=images.nikolay.office.blabla.ru
UPPYSERVER_DATADIR=app/storage

UPPYSERVER_PROTOCOL=https

UPPYSERVER_GOOGLE_KEY=blabla.apps.googleusercontent.com
UPPYSERVER_GOOGLE_SECRET=blabla

UPPYSERVER_INSTAGRAM_KEY=blabla
UPPYSERVER_INSTAGRAM_SECRET=blabla

UPPYSERVER_OAUTH_DOMAIN=images.nikolay.office.blabla.ru

DOMAIN_UPPY=images.nikolay.office.blabla.ru
```

Please keep in mind that instagram provider works perfect, i'm facing issues only with Google Drive

**Comment by ifedapoolarewaju** [comment]
If this issue is only with google drive then it is most likely you set the wrong redirect_uri on your google drive dashboard. Can you confirm if that’s the case?

**Comment by elluminatte** [comment]
@ifedapoolarewaju but i don't specify the redirect_uri in API console. i only specify the authorized URIs list. I've added the URI, that is generated by uppy server in this list.
So i think that redirect uri is controlled by uppy-server, am i wrong?

**Comment by elluminatte** [comment]
@ifedapoolarewaju i see this string in library test file (test/__tests__/provider-manager.js):

_expect(grantConfig.google.redirect_uri).toBe('http://domain.com/google/redirect')_

This is the URI, that i see in browser address string, then i think that it's not really Drive Dashboard tuning issue.

**Comment by ifedapoolarewaju** [comment]
I am currently responding from my mobile so I’m unable to do much, one suggestion would be to drop the UPPYSERVER_OAUTH_DOMAIN config if you don't have multiple instances of your server running. 

Perhaps there’s a bug somewhere in the Multiple instance redirect channeling for google drive (I can’t confirm till I get to my machine) but I know for sure that it works right for single instance setting.

So simply drop the UPPYSERVER_OAUTH_DOMAIN config and see if it works

**Comment by elluminatte** [comment]
LOL i've just figured out the same issue. 

There are these lines in src/server/provider/index.js file:

```js
if (oauthDomain) {
        grantConfig[providerName].redirect_uri = `${server.protocol}://${oauthDomain}/${providerName}/redirect`
}
```

Then redirectUrl becomes https://blabla/google/redirect, and uppy tries to find google provider, while it should be drive.

I've temporary removed  UPPYSERVER_OAUTH_DOMAIN setting, described issue has been resolved. But now nothing happens after auth - i login with google account, then i was redirected to my site but button on Uppy Dashboard says "PLEASE AUTHENTICATE WITH GOOGLE DRIVE
TO SELECT FILES". Again and again... No errors in console or in docker log.

Could you check that Google Drive provider really works with latest uppy-server release?

**Comment by ifedapoolarewaju** [comment]
Does instagram work with this change?

**Comment by elluminatte** [comment]
@ifedapoolarewaju yep. Instagram still works properly

**Comment by ifedapoolarewaju** [comment]
Ok, my hands are a bit tied right now, let me suggest a more reasonable solution in a couple hours when I get back to my machine.

Is that ok?

**Comment by elluminatte** [comment]
@ifedapoolarewaju no problem! This is opensource project anyway lol.
Thank you!

**Comment by ifedapoolarewaju** [comment]
@elluminatte did you make any progress with this? I can confirm that the GoogleDrive provider is working fine as at the last release. Maybe there's still something up with your configuration? Did you restart the docker instance after updating the config?

PS. This difficulty in debugging would no longer be so by the next release, as I have added a `debug` flag functionality, that would help one get more detailed logs on every level/layer the server routing process passes through.

**Comment by elluminatte** [comment]
@ifedapoolarewaju hi
have not figured out anything new.
looks like google authorization finishes successfully, but uppy doesnt see auth state - after auth with google dashboard says: "PLEASE AUTHENTICATE WITH GOOGLE DRIVE TO SELECT FILES". If i click button, i'm being immediately redirected to site (so i think auth is completed). Again and again.
May be reason is related with Uppy frontend code? I'm using bundled version from your CDN

**Comment by elluminatte** [comment]
@ifedapoolarewaju this is network log - Demo on your site VS uppy on my site. I see requesting /drive/root in demo, vs 3 ones of /authorize on my site 

![4](https://user-images.githubusercontent.com/8599788/33544451-e0cff4e8-d8eb-11e7-89ac-ca94d37fd236.png)

![5](https://user-images.githubusercontent.com/8599788/33544452-e0ec57b4-d8eb-11e7-9988-f2be931f900c.png)

**Comment by ifedapoolarewaju** [comment]
@elluminatte I am unable to reproduce this issue on my end, since instagram provider works for you, this is most likely an issue with your google provider set up. 

Can you confirm you have a URL of the form `<protocol>://<yourhost>/connect/google/callback`
as authorized url on your google api console?

This is usually what you would set if you are not making use of the `UPPYSERVER_OAUTH_DOMAIN` option

**Comment by elluminatte** [comment]
@ifedapoolarewaju hi. yes, URL is confirmed in console of course

**Comment by ifedapoolarewaju** [comment]
Hmm, now I'm running out of ideas, what version of the uppy client are you running?

**Comment by elluminatte** [comment]
@ifedapoolarewaju i'm using latest v 0.21.0

**Comment by elluminatte** [comment]
@ifedapoolarewaju this was not really uppy issue. I've added _console.log(err)_ in _server/controllers/authorized.js_, then i've seen the error reason: "_Access Not Configured. Drive API has not been used in project xxxx before or it is disabled_". So after enabling it works OK.

Anyway could you please implement error loging for similar situations in future - as we have seen it's very hard to debug
