### ISSUE TITLE
how to connect my rails app with parallel running uppy-server

### ISSUE THREAD

**Issue by dersar00** [transloadit/uppy-server#47]
Hello!
I have my rails app, where I run uppy, but i need to use dropbox, google drive, instagam and others cloud storage,  and I run a stand-alone uppy server in parallel running, I start it together it in my procfile. How i can connect my rails app and uppy-server. Please don't offer me transloadit, I need to solve my problem.

**Comment by kvz** [comment]
Hi, you don't have to connect them. uppy-server acts as a sidecart to the Uppy client, independent of your rails app. the rails app will just receive either tus or xhr uploads from both.

**Comment by janko** [comment]
@dersar00 uppy-server is a just web application that runs on localhost its own port, and you connect uppy with uppy-server by setting the `:host` option for provider plugins to the uppy-server, as instructed in the [documentation](https://uppy.io/docs/plugins/#Provider-Plugins).

The setup doesn't depend on whether your running Rails or any other web framework in any other language, there is nothing Rails-specific about it, it's all done on the client side. As a matter of fact, if you're using uppy-server, there is zero Rails configuration you need to do for *any* uppy feature.
