### ISSUE TITLE
Trouble with connecting to google drive

### ISSUE THREAD

**Issue by dersar00** [transloadit/uppy-server#53]
Hello, i have some troubles with connect to google drive.
I run standalone uppy server(localhost:3020) parallel to my rails app(localhost:5000), I registered in console.developers.google.com, create a new project.
![image](https://user-images.githubusercontent.com/17855733/34936254-5ae2438a-f9e9-11e7-8fbc-3c01ec5e3b8c.png)
The Client I paste to "UPPYSERVER_GOOGLE_KEY", Client secret I paste to "UPPYSERVER_GOOGLE_SECRET".
Have I filled everything correctly? Have i filled correctly "Authorized JavaScript origins
" field? When i try to to Connect to Google Drive I get this error: 
![image](https://user-images.githubusercontent.com/17855733/34937022-ff53fe84-f9eb-11e7-8ed7-c2fd580aa435.png)
What am I doing wrong?

**Comment by ifedapoolarewaju** [comment]
Hi @dersar00 you need to set this as your authorized redirect uri

`http://localhost:3020/drive/callback`

**Comment by dersar00** [comment]
Thanks, @ifedapoolarewaju , but uri must look like this
 http://localhost:3020/connect/google/callback

**Comment by ifedapoolarewaju** [comment]
yes the url should be `http://localhost:3020/connect/google/callback`, excuse my mistake.
