### ISSUE TITLE
Trouble with uploading from google drive

### ISSUE THREAD

**Issue by dersar00** [transloadit/uppy-server#54]
Hello, when i'm connecting to google drive, select a jpg file and after i start to upload this file I get this error and my server shutting down.
![image](https://user-images.githubusercontent.com/17855733/34943141-19872b02-fa03-11e7-8425-ad3714b322c9.png)

**Comment by ifedapoolarewaju** [comment]
@dersar00 it seems the upload request to the multipart server returns an error. Can you check if the request reaches your multipart server?

Also can you share your uppy-client code here?

**Comment by dersar00** [comment]
@ifedapoolarewaju 
my uppy-clien code: https://pastebin.com/59P6JjAn

**Comment by ifedapoolarewaju** [comment]
`.use(XHRUpload, {endpoint: "/files/upload", fieldName: 'file', formData: true})`

@dersar00 your `endpoint` should be a full url as in "http://localhost:5000/files/upload"

**Comment by dersar00** [comment]
@ifedapoolarewaju it's doesn't help now it's look like this
![image](https://user-images.githubusercontent.com/17855733/34945189-20499530-fa0b-11e7-9047-fefa77c68884.png)

**Comment by ifedapoolarewaju** [comment]
@dersar00 there's a bug in there indeed that prevents us from seeing the error because we are trying to log an undefined `response.statusCode` along with it. I am going to release a patch to fix this.

I'm going to do this in a couple hours and you can update and try this again. Is that ok? 🙂

**Comment by ifedapoolarewaju** [comment]
I have published a patch for this at `v0.10.1`. Please run `npm install uppy-server@0.10.1` to install and try this again?

**Comment by dersar00** [comment]
Thanks, bro!
I try it tomorrow, and will report result here.

**Comment by dersar00** [comment]
@ifedapoolarewaju i run uppy server as standalone, after updating code, i can't run it.
![image](https://user-images.githubusercontent.com/17855733/34977851-e61a4d9c-faa4-11e7-872a-519fbbc043f2.png)

**Comment by ifedapoolarewaju** [comment]
@dersar00 did you update via `npm` or are you using github?

If you are using github then it means you also inherited the other new changes, so please start the server with `npm start` instead of `npm run start:production` (this has been changed). Sorry for the confusion.

**Comment by dersar00** [comment]
![image](https://user-images.githubusercontent.com/17855733/34978741-ee264b00-faa7-11e7-9066-3e6c225cd5a1.png)

**Comment by dersar00** [comment]
@ifedapoolarewaju When I start with `npm start` it's return me a similar error.

**Comment by dersar00** [comment]
@ifedapoolarewaju try to run server as standalone after cloning from github.

**Comment by ifedapoolarewaju** [comment]
how are you loading your uppy config? do you have an `env.sh` file that you need to update?

**Comment by ifedapoolarewaju** [comment]
or perhaps you need to run the config script before starting the server like so:

`sh env.sh && npm start`

**Comment by dersar00** [comment]
@ifedapoolarewaju Yes, I have  `env.sh` file.
This is something incredible, when i run first with command `sh env.sh && npm start` it's starts well, but after i try reload it, it's return me error.
![image](https://user-images.githubusercontent.com/17855733/34979530-36d93e28-faaa-11e7-904d-125b152c8773.png)
Now i get a similar error when I try to start this with command `npm start`.

**Comment by ifedapoolarewaju** [comment]
yes, it's saying the port `3020` is already in use. This is because you still have the server running somewhere else maybe? And you are trying to start it again without killing the currently running one?

**Comment by dersar00** [comment]
I don't know why it's return me this error, because in browser when i opening `http://localhost:3020/` it's don't open me anything.
So, ok, I had open 2 term tabs, after I rerun term and try to start the server it's again return me error.
![image](https://user-images.githubusercontent.com/17855733/34980153-41858a96-faac-11e7-9e47-3aa264f0e34a.png)

**Comment by ifedapoolarewaju** [comment]
@dersar00 are these options set in the env.sh file?

`UPPYSERVER_SECRET`
`UPPYSERVER_DOMAIN`
`UPPYSERVER_DATADIR`

**Comment by dersar00** [comment]
@ifedapoolarewaju Yes.

**Comment by ifedapoolarewaju** [comment]
try `source env.sh && npm start` instead

**Comment by dersar00** [comment]
@ifedapoolarewaju One step is done, it's starts.
So now when i try to upload file from google drive, comparatively with yesterdays error it's don't stop my server, but return me error 
![image](https://user-images.githubusercontent.com/17855733/34981088-1e6dc70a-faaf-11e7-842e-c439698e91a0.png)
![image](https://user-images.githubusercontent.com/17855733/34981158-5f3e755e-faaf-11e7-9cdb-fb28e72a45a0.png)

**Comment by ifedapoolarewaju** [comment]
yeah it seems you are not setting the endpoint url the right way? Did you change the uppy client code from yesterday? Can you paste what the code now looks like?

**Comment by dersar00** [comment]
@ifedapoolarewaju it's here https://pastebin.com/n3WUwyi9

**Comment by ifedapoolarewaju** [comment]
this url links to probably your `env.sh` instead 🙂

**Comment by dersar00** [comment]
@ifedapoolarewaju Yes, sorry I'm misunderstood.
https://pastebin.com/ABRnEpzn

**Comment by ifedapoolarewaju** [comment]
hmm it seems to be related to this https://github.com/nodejs/node/issues/5436 . It works with no issues on my machine. What version of node are you running? What OS are you running?

**Comment by dersar00** [comment]
@ifedapoolarewaju `node resion - v9.4.0`
mac OS Siera 10.12.6

**Comment by dersar00** [comment]
I change XHRUpload to Tus and it starts work correct.

**Comment by jsrj** [comment]
Not sure if it is a similar issue or not, but even in using the "Getting Started" section on transloadit.com, it fails to upload and when reading the details, I get:


error | CLOUDFILES_STORE_ERROR
message | Transloadit was unable to store the given file in the container.
reason | One of our commands reported an error. with code undefined: undefined

**Comment by ifedapoolarewaju** [comment]
Hi @jsrj this seems like it could rather be an issue with the Assembly instructions you are sending to Transloadit. Could you share the code snippet you are using?

**Comment by kvz** [comment]
Hi there, about CLOUDFILES_STORE_ERROR, another user reported this error and it was because they had not specified the rackspace datacenter along with their store instructions. It seems Rackspace may have made a breaking change meaning this now is required. Could this be the case for you as well?
