### ISSUE TITLE
stop uppy-server

### ISSUE THREAD

**Issue by floodico** [transloadit/uppy-server#55]
Hello there!
I'm using uppy-server as standalone server and running him from Procfile of my project. And sometimes when i stop my own server, uppy-server doesn't stop. Then i must delete running command of uppy-server from Procfile. That's very not comfortably. How can i stop uppy-server manually?

**Comment by kvz** [comment]
Hi there, uppy server is a 'normal' process so it can be stopped by whoever launches it, so I'm afraid this is more of a Procfile question, but i am unfamiliar with Procfile. Anyone else?

**Comment by ifedapoolarewaju** [comment]
since you are using the procfile, then you are most likely on heroku. I imagine you could have your procfile similar to this.

```
web: <your rails server command>
uppy: <your uppy-server command>
```

then you can stop the uppy-server from your heroku cli like so:

`heroku ps:scale uppy=0`

Note the name `uppy` is corresponding to the label given to it in the procfile.

**Comment by floodico** [comment]
thank you @ifedapoolarewaju, and what about localhost?

**Comment by ifedapoolarewaju** [comment]
@floodico are you using foreman? If yes, then you can follow one of these ideas [here](https://stackoverflow.com/questions/20190152/killing-processes-spawned-by-foreman).

But this is really not an issue with uppy-server, but with foreman itself : )

**Comment by ifedapoolarewaju** [comment]
closing this as it actually isn't an uppy-server issue
