### ISSUE TITLE
does uppy-server support multipart?

### ISSUE THREAD

**Issue by musicformellons** [transloadit/uppy-server#56]
Uppy-server has body-parser as a dependency. On their [repo](https://github.com/expressjs/body-parser) I find that it 

> does not handle multipart bodies

As a total nitwit in this area this kind of suprises me? Does uppy-server not require something like [multer](https://github.com/expressjs/multer) to facilitate multipart. This idea of mine stems from [this article](https://docs.feathersjs.com/guides/advanced/file-uploading.html#feathers-blob-with-multipart-support).

**Comment by kvz** [comment]
Hi there. Uppy server does not receive files. It’s a proxy for fetching from Eg dropbox. The receiver is your Eg Apache server or a tusd server

**Comment by musicformellons** [comment]
Ah! So to have 'a complete' file storage solution I need to install e.g. a tusd server next to uppy-server!?

**Comment by kvz** [comment]
Yeah sorry if it's a bit unclear! If you just need 'regular' uploads, your current webserver will be able to handle any upload from the XhrPlugin. If you addition you want:

+ import from instagram/dropbox/etc: add uppy-server
+ resumable file uploads: add a tus server (can also be ruby/php tus integration, or a standalone server like tusd)

Does that help?

**Comment by musicformellons** [comment]
It is clear now! Thanks!
