### ISSUE TITLE
Can we possibly get less permissions for google drive?

### ISSUE THREAD

**Issue by kvz** [transloadit/uppy-server#63]
Like, read only maybe?

![2018-02-19 at 15 30](https://user-images.githubusercontent.com/26752/36382625-ed87575a-1589-11e8-9f27-27231ef4f6fc.png)

**Comment by ifedapoolarewaju** [comment]
yeah, it's scary I agree. It reads the same when authorizing zapier, and even transloadit.com my youtube account. It seems this UI was recently updated, and maybe they've changed to a more flexible API. I'll investigate
