### ISSUE TITLE
Can we get a more descriptive error when uppy-server cannot be reached

### ISSUE THREAD

**Issue by kvz** [transloadit/uppy-server#64]
<img width="606" alt="screen shot 2018-02-19 at 15 31 43" src="https://user-images.githubusercontent.com/26752/36382660-0c7ad628-158a-11e8-80a9-3cc778a3c2e0.png">

**Comment by kvz** [comment]
In my case, the error was:

> Failed to load https://server.uppy.io/drive/authorized: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://vimeo-uppy.now.sh' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

But it'd be nice to see: `Failed to reach Uppy Server at '<url>'` I think.

**Comment by goto-bus-stop** [comment]
This is probably a client side issue—I think `fetch` purposely doesn't tell JS much about what happened, but we could def do something like "Could not reach Uppy Server" or something.

**Comment by goto-bus-stop** [comment]
Hah. got sniped!

**Comment by ifedapoolarewaju** [comment]
@kvz yes, this seems to me like a client issue no?

**Comment by kvz** [comment]
I think so yes!  - Will move it!

**Comment by kvz** [comment]
Moved to client repo 👌
