### ISSUE TITLE
Should we upgrade to Grant 4?

### ISSUE THREAD

**Issue by kvz** [transloadit/uppy-server#72]
On 14 March 2018 at 15:05:03, Simeon Velichkov (simeonvelichkov@gmail.com) wrote:
> > :wave: I'm the author of Grant
> 
> I've released Grant v4.0, here is the: https://github.com/simov/grant/blob/master/CHANGELOG.md#v400-20180314 
> 
> Internally I've dropped the `request` dependency which will 
> result in:
> 
> - less dependencies
> - lower memory footprint of the HTTP server consuming Grant
> - less vulnerability issues constantly popping out of `request`'s 
> deps
> 
> There should be only one breaking change regarding the error 
> handling in the final callback based on the `transport` type 
> used, which should be set to `session` anyway.
> 
> Let me know if you have any issues!
> 
> 
> Simo

**Comment by simov** [comment]
@kvz, thanks for posting this here, I wasn't sure if that's the right place to do it.

Actually @ifedapoolarewaju already tried to upgrade it and he found a minor issue https://github.com/simov/grant/issues/88 that I've managed to fix in `v4.0.1` :+1:

**Comment by ifedapoolarewaju** [comment]
upgraded
