### ISSUE TITLE
Problem with standalone running

### ISSUE THREAD

**Issue by dersar00** [transloadit/uppy-server#74]
![image](https://user-images.githubusercontent.com/17855733/37825858-ed10c7b0-2e99-11e8-9d0c-57951606ecc3.png)

**Comment by ifedapoolarewaju** [comment]
Hello @dersar00 sorry for the late response on this, but it seems you are not setting the env variables `UPPYSERVER_SECRET`, `UPPYSERVER_DATADIR`, and `UPPYSERVER_DOMAIN`. Please [see](https://uppy.io/docs/server/#Configure-Standalone)

**Comment by ifedapoolarewaju** [comment]
closing due to no response on this.
