### ISSUE TITLE
Add "upload file from OneDrive "

### ISSUE THREAD

**Issue by Aarbel** [transloadit/uppy-server#76]
Many users need it, because many users use Microsoft products :cake:  

- https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file

**It looks like you didn't dare to use the OneDrive api. Is there a reason or is that because no one took the time ?**

Thanks !

**Comment by kvz** [comment]
Hi there, closing this one in favor of https://github.com/transloadit/uppy/issues/730 👌
