### ISSUE TITLE
Lambda Support

### ISSUE THREAD

**Issue by dcflow** [transloadit/uppy-server#77]
Hello,

What do you guys think of uploading the server to Lambda?
How should we approach this, bundle all the `src` together 
or we can strip out some parts.

Thank You!

**Comment by kvz** [comment]
We would like to offer a guide at least, yes, on how people could run this on Lambda. Would you like to take the first swing at that?

**Comment by dcflow** [comment]
It's not for production but it works #78

**Comment by ifedapoolarewaju** [comment]
closing as it has been resolved [here](https://github.com/transloadit/uppy-server/pull/78)
