### ISSUE TITLE
Standalone uppy-server doesn't use HTTPS

### ISSUE THREAD

**Issue by vgiotsas** [transloadit/uppy-server#79]
I'm trying to start the standalone uppy-servrer using HTTPS.
Before starting the server I set the following environment variable:

```
export UPPYSERVER_PROTOCOL="https"
```

But then when I run `npm start` the server uses HTTP, also shown in the server output;:

```
> uppy-server@0.11.2 start /var/www/html/vclass/uppy-server
> node ./lib/standalone/start-server.js

uppy: 2018-04-03T15:55:12.585Z [info] jobs.cleanup.start starting clean up job
Welcome to Uppy Server! v0.11.2
Listening on http://0.0.0.0:3020
^Cubuntu@ip-172-31-36-126:/var/www/html/vclass/uppy-server$ npm start                                                                                                                             
> uppy-server@0.11.2 start /var/www/html/vclass/uppy-server
> node ./lib/standalone/start-server.js

uppy: 2018-04-03T15:55:20.122Z [info] jobs.cleanup.start starting clean up job
Welcome to Uppy Server! v0.11.2
Listening on http://0.0.0.0:3020
```

Do I need to set any other configuration option?

I installed a server letsencrypt SSL certificate using certbot for apache as documented below:
https://certbot.eff.org/lets-encrypt/ubuntuxenial-apache

**Comment by ifedapoolarewaju** [comment]
Hi there, Thank you for reporting! I'm afraid uppy-server does not handle `https` itself. At least not yet. Instead, to use https with uppy-server, you can use a proxy-server such as nginx, or haproxy, which will handle the ssl/tsl business and then forward the request to uppy-server which you would have running internally. This is the way it is done with server.uppy.io

the `UPPYSERVER_PROTOCOL` option is rather to inform uppy about what protocol your server is using, it is not to used to enable `https` as you might have earlier thought.

Sorry for the mixup.

**Comment by ifedapoolarewaju** [comment]
closing this since the question has been answered
