### ISSUE TITLE
Rename `host` and `hostPattern`

### ISSUE THREAD

**Issue by kvz** [transloadit/uppy-server#96]
Host is usually: `jane.transloadit.com` but since `host` in our case contains a full url with many more components (protocol, path, etc), I'd vote to name it `endpoint`.

`hostPattern` could than be named `allowedOrigins` which could either take (an array for a list of flat origins, a function to be executed on a string which returns true or false, or) a RegExp.

The proposals are up for discussion, but I do think a change is needed.

For BC-compat, we could likely still accept `host` and throw a Deprecation warning at the console for a release or two.

**Comment by arturi** [comment]
The only issue with `endpoint` is that we use it in uploader plugins, and that might contribute to a popular misunderstanding that Uppy Server is an upload target. Not an end of the world, just noting.

**Comment by kvz** [comment]
That's a fair point. How about `url` then?

**Comment by arturi** [comment]
`serverUrl` and `serverPattern`? 🤔

**Comment by ifedapoolarewaju** [comment]
I like `url` better. We never used `serverHost`, so maybe no need for `serverUrl` either.

**Comment by ifedapoolarewaju** [comment]
on second thought, serverUrl and serverPattern tells it just right, and avoids any future confusion whatsoever. So I'll go with those instead https://github.com/transloadit/uppy/pull/905

**Comment by ifedapoolarewaju** [comment]
> For BC-compat, we could likely still accept host and throw a Deprecation warning at the console for a release or two.

@kvz do we really need to? Since we are still pre-1.0 and breaking changes are still permitted-ish?

**Comment by kvz** [comment]
That’s fair! I expect some people will upgrade and forget to change, so maybe we can just fail fast and hard when no serverUrl is set. Perhaps this is already the case (for host, currently). Then we can just rename, note Breaking in the changelog and be done with it 👌

**Comment by ifedapoolarewaju** [comment]
done here https://github.com/transloadit/uppy/pull/905
